-- NOVA SQUAD — FRESH RESET + DATABASE SETUP
-- WARNING: this intentionally removes the current tournament tables/data.
-- Run this once in Supabase SQL Editor for a completely clean start.

drop table if exists public.tournament_entries cascade;
drop table if exists public.leaderboard cascade;
drop table if exists public.admin_settings cascade;
drop table if exists public.teams cascade;

create table public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null unique,
  captain text not null,
  phone text not null,
  players jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.leaderboard (
  team_id bigint primary key references public.teams(id) on delete cascade,
  played integer not null default 0,
  kills integer not null default 0,
  points integer not null default 0
);

create table public.tournament_entries (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  tournament text not null,
  amount integer not null default 200,
  payer_name text not null,
  utr text not null,
  status text not null default 'PENDING' check (status in ('PENDING','PAID','REJECTED')),
  created_at timestamptz not null default now()
);

create unique index tournament_entries_team_tournament_idx
on public.tournament_entries(team_id,tournament);

create table public.admin_settings (
  id integer primary key default 1 check (id=1),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

-- Initial admin password: Admin@123
-- Change it immediately after first login.
insert into public.admin_settings(id,password_hash)
values (1,'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2e3acc7')
;

alter table public.teams enable row level security;
alter table public.leaderboard enable row level security;
alter table public.tournament_entries enable row level security;
alter table public.admin_settings enable row level security;
