-- NOVA SQUAD TOURNAMENT — fresh Supabase setup
-- Run once in Supabase SQL Editor.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  team_name text not null unique,
  captain text not null,
  phone text not null,
  players jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.leaderboard (
  team_id bigint primary key references public.teams(id) on delete cascade,
  played integer not null default 0,
  kills integer not null default 0,
  points integer not null default 0
);

create table if not exists public.tournament_entries (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  tournament text not null,
  amount integer not null default 200,
  payer_name text not null,
  utr text not null,
  status text not null default 'PENDING' check (status in ('PENDING','PAID','REJECTED')),
  created_at timestamptz not null default now()
);

create unique index if not exists tournament_entries_team_tournament_idx
on public.tournament_entries(team_id,tournament);

create table if not exists public.admin_settings (
  id integer primary key default 1 check (id=1),
  password_hash text not null,
  updated_at timestamptz not null default now()
);

-- Initial admin password: Admin@123
-- Change it immediately from Admin Panel after first login.
insert into public.admin_settings(id,password_hash)
values (1,'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7')
on conflict (id) do nothing;

-- Backend uses the Supabase secret key, so browser clients do not need direct table access.
alter table public.teams enable row level security;
alter table public.leaderboard enable row level security;
alter table public.tournament_entries enable row level security;
alter table public.admin_settings enable row level security;
